name: todolist-deployment
run-name: ${{ github.actor }} - ${{ github.ref_name }}
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

env:
  PYTHON_VERSION: 3.8

jobs:
  python-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: '${{ env.PYTHON_VERSION }}'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 pytest coverage

    - name: Run tests
      run: |
        cd ./api
        pytest

    - name: Generate coverage report
      run: |
        cd ./api
        coverage run -m pytest
        coverage report

    - name: Display coverage report
      run: |
        coverage report -m

    - name: Check code style
      run: |
        flake8 .

    - name: Check code complexity
      run: |
        flake8 --max-complexity 10

    - name: Upload Python code as artifact
      uses: actions/upload-artifact@v4
      with:
        name: python-code
        path: .

